/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 06:09:44 PM CST 
//

package com.dell.isg.smi.wsmanclient.wsman.errormessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SOURCE_PROPERTY" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="attribute name"/>
 *             &lt;enumeration value="device name"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NAME" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="arg1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DATATYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="string"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DYNAMIC_ELEMENT")
public class DYNAMICELEMENT {

    @XmlAttribute(name = "SOURCE_PROPERTY", required = true)
    protected String sourceproperty;
    @XmlAttribute(name = "NAME", required = true)
    protected String name;
    @XmlAttribute(name = "DATATYPE", required = true)
    protected String datatype;


    /**
     * Gets the value of the sourceproperty property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSOURCEPROPERTY() {
        return sourceproperty;
    }


    /**
     * Sets the value of the sourceproperty property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSOURCEPROPERTY(String value) {
        this.sourceproperty = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNAME() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNAME(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the datatype property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDATATYPE() {
        return datatype;
    }


    /**
     * Sets the value of the datatype property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDATATYPE(String value) {
        this.datatype = value;
    }

}
