/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 06:09:44 PM CST 
//

package com.dell.isg.smi.wsmanclient.wsman.errormessage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}CIMSTATUSCODE"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}ERROR_TYPE"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}ERROR_SOURCE"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}RECOMMENDED_ACTION" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ERROR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cimstatuscode", "errortype", "errorsource", "recommendedaction" })
@XmlRootElement(name = "FIXED_MESSAGE_INSTANCE_VALUES")
public class FIXEDMESSAGEINSTANCEVALUES {

    @XmlElement(name = "CIMSTATUSCODE", required = true)
    protected CIMSTATUSCODE cimstatuscode;
    @XmlElement(name = "ERROR_TYPE", required = true)
    protected ERRORTYPE errortype;
    @XmlElement(name = "ERROR_SOURCE", required = true)
    protected ERRORSOURCE errorsource;
    @XmlElement(name = "RECOMMENDED_ACTION", required = true)
    protected List<RECOMMENDEDACTION> recommendedaction;
    @XmlAttribute(name = "TYPE", required = true)
    protected String type;


    /**
     * Gets the value of the cimstatuscode property.
     * 
     * @return possible object is {@link CIMSTATUSCODE }
     * 
     */
    public CIMSTATUSCODE getCIMSTATUSCODE() {
        return cimstatuscode;
    }


    /**
     * Sets the value of the cimstatuscode property.
     * 
     * @param value allowed object is {@link CIMSTATUSCODE }
     * 
     */
    public void setCIMSTATUSCODE(CIMSTATUSCODE value) {
        this.cimstatuscode = value;
    }


    /**
     * Gets the value of the errortype property.
     * 
     * @return possible object is {@link ERRORTYPE }
     * 
     */
    public ERRORTYPE getERRORTYPE() {
        return errortype;
    }


    /**
     * Sets the value of the errortype property.
     * 
     * @param value allowed object is {@link ERRORTYPE }
     * 
     */
    public void setERRORTYPE(ERRORTYPE value) {
        this.errortype = value;
    }


    /**
     * Gets the value of the errorsource property.
     * 
     * @return possible object is {@link ERRORSOURCE }
     * 
     */
    public ERRORSOURCE getERRORSOURCE() {
        return errorsource;
    }


    /**
     * Sets the value of the errorsource property.
     * 
     * @param value allowed object is {@link ERRORSOURCE }
     * 
     */
    public void setERRORSOURCE(ERRORSOURCE value) {
        this.errorsource = value;
    }


    /**
     * Gets the value of the recommendedaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recommendedaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRECOMMENDEDACTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RECOMMENDEDACTION }
     * 
     * 
     */
    public List<RECOMMENDEDACTION> getRECOMMENDEDACTION() {
        if (recommendedaction == null) {
            recommendedaction = new ArrayList<RECOMMENDEDACTION>();
        }
        return this.recommendedaction;
    }


    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTYPE() {
        return type;
    }


    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTYPE(String value) {
        this.type = value;
    }

}
