/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 06:09:44 PM CST 
//

package com.dell.isg.smi.wsmanclient.wsman.errormessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SEQUENCE_NUMBER" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="11"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="14"/>
 *             &lt;enumeration value="15"/>
 *             &lt;enumeration value="16"/>
 *             &lt;enumeration value="17"/>
 *             &lt;enumeration value="18"/>
 *             &lt;enumeration value="19"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="21"/>
 *             &lt;enumeration value="22"/>
 *             &lt;enumeration value="23"/>
 *             &lt;enumeration value="24"/>
 *             &lt;enumeration value="25"/>
 *             &lt;enumeration value="26"/>
 *             &lt;enumeration value="27"/>
 *             &lt;enumeration value="28"/>
 *             &lt;enumeration value="29"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="30"/>
 *             &lt;enumeration value="31"/>
 *             &lt;enumeration value="32"/>
 *             &lt;enumeration value="33"/>
 *             &lt;enumeration value="34"/>
 *             &lt;enumeration value="35"/>
 *             &lt;enumeration value="36"/>
 *             &lt;enumeration value="37"/>
 *             &lt;enumeration value="38"/>
 *             &lt;enumeration value="39"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="40"/>
 *             &lt;enumeration value="41"/>
 *             &lt;enumeration value="42"/>
 *             &lt;enumeration value="43"/>
 *             &lt;enumeration value="44"/>
 *             &lt;enumeration value="45"/>
 *             &lt;enumeration value="46"/>
 *             &lt;enumeration value="47"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="49"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="50"/>
 *             &lt;enumeration value="51"/>
 *             &lt;enumeration value="52"/>
 *             &lt;enumeration value="53"/>
 *             &lt;enumeration value="54"/>
 *             &lt;enumeration value="55"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="9"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PREFIX" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="BIOS"/>
 *             &lt;enumeration value="BOOT"/>
 *             &lt;enumeration value="CCR"/>
 *             &lt;enumeration value="DH"/>
 *             &lt;enumeration value="JCP"/>
 *             &lt;enumeration value="LC"/>
 *             &lt;enumeration value="NIC"/>
 *             &lt;enumeration value="OSD"/>
 *             &lt;enumeration value="RED"/>
 *             &lt;enumeration value="STOR"/>
 *             &lt;enumeration value="STOR "/>
 *             &lt;enumeration value="SUP"/>
 *             &lt;enumeration value="SUP "/>
 *             &lt;enumeration value="VF"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MESSAGE_ID")
public class MESSAGEID {

    @XmlAttribute(name = "SEQUENCE_NUMBER", required = true)
    protected byte sequencenumber;
    @XmlAttribute(name = "PREFIX", required = true)
    protected String prefix;


    /**
     * Gets the value of the sequencenumber property.
     * 
     */
    public byte getSEQUENCENUMBER() {
        return sequencenumber;
    }


    /**
     * Sets the value of the sequencenumber property.
     * 
     */
    public void setSEQUENCENUMBER(byte value) {
        this.sequencenumber = value;
    }


    /**
     * Gets the value of the prefix property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPREFIX() {
        return prefix;
    }


    /**
     * Sets the value of the prefix property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPREFIX(String value) {
        this.prefix = value;
    }

}
