/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 06:09:44 PM CST 
//

package com.dell.isg.smi.wsmanclient.wsman.errormessage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dell.esg.icee.common.protocol.wsman.errormessage package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OWNINGENTITY_QNAME = new QName("http://schemas.dmtf.org/wbem/messageregistry/1", "OWNING_ENTITY");
    private final static QName _DESCRIPTION_QNAME = new QName("http://schemas.dmtf.org/wbem/messageregistry/1", "DESCRIPTION");
    private final static QName _STATICELEMENT_QNAME = new QName("http://schemas.dmtf.org/wbem/messageregistry/1", "STATIC_ELEMENT");
    private final static QName _MESSAGEDESCRIPTION_QNAME = new QName("http://schemas.dmtf.org/wbem/messageregistry/1", "MESSAGE_DESCRIPTION");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.esg.icee.common.protocol.wsman.errormessage
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link DYNAMICELEMENT }
     * 
     */
    public DYNAMICELEMENT createDYNAMICELEMENT() {
        return new DYNAMICELEMENT();
    }


    /**
     * Create an instance of {@link MESSAGEID }
     * 
     */
    public MESSAGEID createMESSAGEID() {
        return new MESSAGEID();
    }


    /**
     * Create an instance of {@link REGISTRYENTRIES }
     * 
     */
    public REGISTRYENTRIES createREGISTRYENTRIES() {
        return new REGISTRYENTRIES();
    }


    /**
     * Create an instance of {@link IDENTIFICATION }
     * 
     */
    public IDENTIFICATION createIDENTIFICATION() {
        return new IDENTIFICATION();
    }


    /**
     * Create an instance of {@link ERRORSOURCE }
     * 
     */
    public ERRORSOURCE createERRORSOURCE() {
        return new ERRORSOURCE();
    }


    /**
     * Create an instance of {@link SPECIFICATION }
     * 
     */
    public SPECIFICATION createSPECIFICATION() {
        return new SPECIFICATION();
    }


    /**
     * Create an instance of {@link MESSAGECOMPONENTS }
     * 
     */
    public MESSAGECOMPONENTS createMESSAGECOMPONENTS() {
        return new MESSAGECOMPONENTS();
    }


    /**
     * Create an instance of {@link RECOMMENDEDACTION }
     * 
     */
    public RECOMMENDEDACTION createRECOMMENDEDACTION() {
        return new RECOMMENDEDACTION();
    }


    /**
     * Create an instance of {@link CIMSTATUSCODE }
     * 
     */
    public CIMSTATUSCODE createCIMSTATUSCODE() {
        return new CIMSTATUSCODE();
    }


    /**
     * Create an instance of {@link MESSAGE }
     * 
     */
    public MESSAGE createMESSAGE() {
        return new MESSAGE();
    }


    /**
     * Create an instance of {@link FIXEDMESSAGEINSTANCEVALUES }
     * 
     */
    public FIXEDMESSAGEINSTANCEVALUES createFIXEDMESSAGEINSTANCEVALUES() {
        return new FIXEDMESSAGEINSTANCEVALUES();
    }


    /**
     * Create an instance of {@link REGISTRYDECLARATION }
     * 
     */
    public REGISTRYDECLARATION createREGISTRYDECLARATION() {
        return new REGISTRYDECLARATION();
    }


    /**
     * Create an instance of {@link ERRORTYPE }
     * 
     */
    public ERRORTYPE createERRORTYPE() {
        return new ERRORTYPE();
    }


    /**
     * Create an instance of {@link REGISTRY }
     * 
     */
    public REGISTRY createREGISTRY() {
        return new REGISTRY();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/messageregistry/1", name = "OWNING_ENTITY")
    public JAXBElement<String> createOWNINGENTITY(String value) {
        return new JAXBElement<String>(_OWNINGENTITY_QNAME, String.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/messageregistry/1", name = "DESCRIPTION")
    public JAXBElement<String> createDESCRIPTION(String value) {
        return new JAXBElement<String>(_DESCRIPTION_QNAME, String.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/messageregistry/1", name = "STATIC_ELEMENT")
    public JAXBElement<String> createSTATICELEMENT(String value) {
        return new JAXBElement<String>(_STATICELEMENT_QNAME, String.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/messageregistry/1", name = "MESSAGE_DESCRIPTION")
    public JAXBElement<String> createMESSAGEDESCRIPTION(String value) {
        return new JAXBElement<String>(_MESSAGEDESCRIPTION_QNAME, String.class, null, value);
    }

}
