/**
 * Copyright © 2017 DELL Inc. or its subsidiaries. All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.31 at 06:09:44 PM CST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wbem/messageregistry/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dell.isg.smi.wsmanclient.wsman.errormessage;
