/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.31 at 06:09:44 PM CST 
//

package com.dell.isg.smi.wsmanclient.wsman.errormessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}REGISTRY_DECLARATION"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/messageregistry/1}REGISTRY_ENTRIES"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "registrydeclaration", "registryentries" })
@XmlRootElement(name = "REGISTRY")
public class REGISTRY {

    @XmlElement(name = "REGISTRY_DECLARATION", required = true)
    protected REGISTRYDECLARATION registrydeclaration;
    @XmlElement(name = "REGISTRY_ENTRIES", required = true)
    protected REGISTRYENTRIES registryentries;


    /**
     * Gets the value of the registrydeclaration property.
     * 
     * @return possible object is {@link REGISTRYDECLARATION }
     * 
     */
    public REGISTRYDECLARATION getREGISTRYDECLARATION() {
        return registrydeclaration;
    }


    /**
     * Sets the value of the registrydeclaration property.
     * 
     * @param value allowed object is {@link REGISTRYDECLARATION }
     * 
     */
    public void setREGISTRYDECLARATION(REGISTRYDECLARATION value) {
        this.registrydeclaration = value;
    }


    /**
     * Gets the value of the registryentries property.
     * 
     * @return possible object is {@link REGISTRYENTRIES }
     * 
     */
    public REGISTRYENTRIES getREGISTRYENTRIES() {
        return registryentries;
    }


    /**
     * Sets the value of the registryentries property.
     * 
     * @param value allowed object is {@link REGISTRYENTRIES }
     * 
     */
    public void setREGISTRYENTRIES(REGISTRYENTRIES value) {
        this.registryentries = value;
    }

}
